# -*- coding: utf-8 -*-
"""asm2tt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S7pGDVi9n5fW3MisHZ72fhChDR82GA3l
"""

# Commented out IPython magic to ensure Python compatibility.
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import random

import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline
plt.style.use('ggplot')

onefig_size = (10,4)
multifigs_size = (12,4)

original_df = pd.read_csv('/content/drive/MyDrive/BI/Lab01-20230710T090521Z-001/asm2/styles.csv')
original_df.head(10)

original_df.shape

df = pd.DataFrame(original_df)

original_df.info()

set(original_df['Branch'])

set(original_df['gender'])

set(original_df['baseColour'])

set(original_df['season'])

set(original_df['usage'])

original_df.describe()

original_df.describe(include='object')

f10000rows = original_df.head(1000)

f1000rows = original_df.head(1000)
plt.figure(figsize=onefig_size)
plt.hist(f10000rows[' Price'], bins=20, color='skyblue')
plt.xlabel(' Price')
plt.ylabel('Frequency')
plt.title('Histogram: Price Distribution ')
plt.show()

plt.figure(figsize=onefig_size)
plt.hist(f10000rows['Sales'], bins=20, color='lightgreen')
plt.xlabel('Sales')
plt.ylabel('Frequency')
plt.title('Histogram: Sales Distribution')
plt.show()

plt.figure(figsize=onefig_size)
review_score_counts = f1000rows['review_score'].value_counts().sort_index()
plt.plot(review_score_counts.index, review_score_counts.values, marker='o', color='salmon')
plt.xlabel('Review Score')
plt.ylabel('Frequency')
plt.title('Line Chart: Review Score Distribution')
plt.show()

plt.figure(figsize=onefig_size)
plt.scatter(f10000rows[' Price'], f10000rows['Sales'], color='coral')
plt.xlabel(' Price')
plt.ylabel('Sales')
plt.title('Scatter Plot: Price vs. Sales')
plt.show()

# Ví dụ 2: Phân tích Bi-Variate cho cột 'Price' và 'review_score' trên 1000 dòng đầu tiên
plt.figure(figsize=onefig_size)
review_score_avg = f10000rows.groupby(' Price')['review_score'].mean()
plt.plot(review_score_avg.index, review_score_avg.values, marker='o', color='lightgreen')
plt.xlabel(' Price')
plt.ylabel('Average Review Score')
plt.title('Line Chart: Price vs. Average Review Score')
plt.show()

first_400_rows = original_df.head(400)
plt.figure(figsize=multifigs_size)
review_score_avg_by_category = first_400_rows.groupby('Category')['review_score'].mean()
plt.bar(review_score_avg_by_category.index, review_score_avg_by_category.values, color='lightblue')
plt.xlabel('Category')
plt.ylabel('Average Review Score')
plt.title('Bar Chart: Average Review Score by Category ')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(data=original_df.head(500), x='season', y=' Price', palette='Set2')
plt.xlabel('Season')
plt.ylabel(' Price')
plt.title('Box Plot: Price by Season')
plt.show()

# Ví dụ 1: Phân tích Multi-variate cho cột 'Price', 'Sales' và 'review_score'
plt.figure(figsize=(10, 6))
sns.scatterplot(data=original_df.head(1000), x=' Price', y='Sales', hue='review_score', size='review_score', sizes=(30, 200), palette='viridis')
plt.xlabel(' Price')
plt.ylabel('Sales')
plt.title('Scatter Plot: Price vs. Sales (Color-coded by Review Score, Size by Review Score)')
plt.legend(title='Review Score')
plt.show()

# Ví dụ 4: Phân tích Multi-Variate cho cột 'year', 'season', và 'Sales'
plt.figure(figsize=(10, 6))
sns.lineplot(data=original_df.head(500), x='year', y='Sales', hue='season', palette='Set2', marker='o')
plt.xlabel('Year')
plt.ylabel('Sales')
plt.title('Line Plot: Sales by Year and Season')
plt.legend(title='Season', loc='upper right')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(data=original_df.head(1000), x='Branch', y='Sales', hue='gender', palette='coolwarm')
plt.xlabel('Branch')
plt.ylabel('Sales')
plt.title('Box Plot: Sales by Branch ')
plt.legend(title='Gender', loc='upper left')
plt.show()

# Ví dụ 2: Phân tích Multi-variate cho cột 'Branch', 'Category', và 'Price'
plt.figure(figsize=(12, 6))
sns.barplot(data=original_df.head(25), x='Branch', y='Sales', hue='Category', ci=None, palette='Set2')
plt.xlabel('Branch')
plt.ylabel('Sales')
plt.title('Bar Chart: Sales by Branch ')
plt.legend(title='Category')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(data=original_df.head(1000), x='season', y='Sales', hue='review_score', palette='coolwarm')
plt.xlabel('Season')
plt.ylabel('Sales')
plt.title('Box Plot: Sales by Season ')
plt.legend(title='Review Score')
plt.show()

# Ví dụ 4: Phân tích BI-Variate cho cột 'gender' và 'Sales'
plt.figure(figsize=(6, 4))
sns.barplot(data=original_df.head(500), x='gender', y='Sales', palette='pastel')
plt.xlabel('Gender')
plt.ylabel('Sales')
plt.title('Sales by Gender')
plt.show()